/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aryaj
 */
public class FormPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form FormPeminjaman
     */
    public FormPeminjaman() {
        initComponents();
        Object[] kolom = {"Judul", "Durasi"};
        DefaultTableModel model = new DefaultTableModel(kolom, 0);
        ArrayList<BukuDipinjam> bukuDipinjam = Perpustakaan.peminjaman.getDaftarBukuDipinjam();
        for (BukuDipinjam buku : bukuDipinjam) {
            Object[] baris = {buku.judul, buku.getLama() + " hari"};
            model.addRow(baris);
        }
        jTableKananDaftarPinjaman.setModel(model);
    }

    public void tampilkan() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    
//    Menampilkan Daftar Buku yang telah dipinjam pada tabel kanan
    public void tampilPinjaman(ArrayList<Buku> bukuList) {
        Object[] kolom = {"Judul"};
        DefaultTableModel model = new DefaultTableModel(kolom, 0);
        for (Buku buku : bukuList) {
            Object[] baris = {buku.judul};
            model.addRow(baris);
        }
        jTableKananDaftarPinjaman.setModel(model);
    }

//    Menampilkan Daftar Buku pada tabel kiri
    public void display(ArrayList<Buku> bukuList) {
        Object[] kolom = {"Judul"};
        DefaultTableModel model = new DefaultTableModel(kolom, 0);
        for (Buku buku : bukuList) {
            Object[] baris = {buku.judul};
            model.addRow(baris);
        }
        jTableKiriDaftarBuku.setModel(model);
    }

//    Menambahkan buku pilihan ke daftar buku yang akan dipinjam
    public void tambahBuku(Buku buku, int lama) {
//        Pengecekan apakah durasi dari buku yang akan dipinjam memenuhi ketentuan
        if (lama > 3 || lama < 1) {
            DialogUI dialogUI = new DialogUI("Lama waktu peminjaman maksimal adalah tiga hari");
            dialogUI.pack();
            dialogUI.setLocationRelativeTo(null);
            dialogUI.setVisible(true);
            return;
        }
//       Inisialisasi Model
        DefaultTableModel modelKanan = (DefaultTableModel) jTableKananDaftarPinjaman.getModel();
        int row = jTableKiriDaftarBuku.getSelectedRow();
        DefaultTableModel modelKiri = (DefaultTableModel) jTableKiriDaftarBuku.getModel();

        String duration = String.format("%d hari", lama);
        
//        Menambahkan buku yang dipilih ke daftar di tabel kanan
        modelKanan.addRow(new Object[]{buku.judul, duration});
//        Menghapus buku yang dipilih dari daftar buku
        modelKiri.removeRow(row);
    }

    public void hapusBuku(Buku buku) {

//        Inisialisasi Model
        DefaultTableModel modelKanan = (DefaultTableModel) jTableKananDaftarPinjaman.getModel();
        DefaultTableModel modelKiri = (DefaultTableModel) jTableKiriDaftarBuku.getModel();
        
        
        int row = jTableKananDaftarPinjaman.getSelectedRow();
//        Pengecekan apakah buku yang dipilih judulnya sesuai dengan buku yang akan dibatalkan di tabel kanan
        if (row >= 0 && buku.judul.equals((String) jTableKananDaftarPinjaman.getValueAt(row, 0))) {
            modelKiri.addRow(new Object[]{buku.judul});
            modelKanan.removeRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldJudulBuku = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKananDaftarPinjaman = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKiriDaftarBuku = new javax.swing.JTable();
        jButtonPinjam = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButtonKonfirmasi = new javax.swing.JButton();
        jTextFieldDurasi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldJudulBuku.setToolTipText("Testt");

        jButtonCari.setText("Cari");
        jButtonCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCariMouseClicked(evt);
            }
        });

        jTableKananDaftarPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableKananDaftarPinjaman);

        jTableKiriDaftarBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableKiriDaftarBuku);

        jButtonPinjam.setText("Pinjam");
        jButtonPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPinjamMouseClicked(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.setMaximumSize(new java.awt.Dimension(68, 25));
        jButtonBatal.setMinimumSize(new java.awt.Dimension(68, 25));
        jButtonBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatalMouseClicked(evt);
            }
        });

        jButtonKonfirmasi.setText("Konfirmasi");
        jButtonKonfirmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKonfirmasiMouseClicked(evt);
            }
        });
        jButtonKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonfirmasiActionPerformed(evt);
            }
        });

        jLabel1.setText("Jumlah Hari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonKonfirmasi)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldJudulBuku, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jButtonPinjam))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jTextFieldDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButtonCari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 161, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonPinjam)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCari)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addComponent(jButtonKonfirmasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCariMouseClicked
        String judul = jTextFieldJudulBuku.getText();
        Perpustakaan.controllerPeminjaman.cariBuku(judul);
    }//GEN-LAST:event_jButtonCariMouseClicked

    private void jButtonPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPinjamMouseClicked
        String judul = (String) jTableKiriDaftarBuku.getValueAt(jTableKiriDaftarBuku.getSelectedRow(), jTableKiriDaftarBuku.getSelectedColumn());
        int lama = Integer.parseInt(jTextFieldDurasi.getText());
        tambahBuku(new Buku(judul), lama);
//        int row = jTableKiriDaftarBuku.getSelectedRow();
        
    }//GEN-LAST:event_jButtonPinjamMouseClicked

    private void jButtonBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatalMouseClicked

        Buku bukutemp = new Buku((String) jTableKananDaftarPinjaman.getValueAt(jTableKananDaftarPinjaman.getSelectedRow(), 0));
        hapusBuku(bukutemp);
    }//GEN-LAST:event_jButtonBatalMouseClicked

    private void jButtonKonfirmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKonfirmasiMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableKananDaftarPinjaman.getModel();

//        Menampilkan pop up message jika buku yang akan dipinjam lebih dari 10 jumlahnya
        if (model.getRowCount() > 10) {
            DialogUI dialogUI = new DialogUI("Jumlah buku yang dipinjam melebihi batas maksimal 10 buku");
            dialogUI.pack();
            dialogUI.setLocationRelativeTo(null);
            dialogUI.setVisible(true);
            return;
        } else {

            int panjangBaris = model.getRowCount();
            ArrayList<BukuDipinjam> bukuDipinjam = new ArrayList<>();
//            int i = 0;
//            for (BukuDipinjam buku : bukuDipinjam) {
////            Object[] baris = {buku.judul};
////            model.addRow(baris);
//                String judul = (String) model.getValueAt(i, 0);
//                String lama = (String) model.getValueAt(i, 1);
//                int lamaInt = Integer.parseInt(lama.split(" ")[0]);
//                bukuDipinjam.add(new BukuDipinjam(judul, lamaInt));
//                i++;
//            }
        for (int i = 0; i < panjangBaris; i++) {
            String judul = (String) model.getValueAt(i, 0);
            String lama = (String) model.getValueAt(i, 1);
            int lamaInt = Integer.parseInt(lama.split(" ")[0]);
            bukuDipinjam.add(new BukuDipinjam(judul, lamaInt));
        }
            Perpustakaan.controllerPeminjaman.pinjam(bukuDipinjam);

        }


    }//GEN-LAST:event_jButtonKonfirmasiMouseClicked

    private void jButtonKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonfirmasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKonfirmasiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonKonfirmasi;
    private javax.swing.JButton jButtonPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableKananDaftarPinjaman;
    private javax.swing.JTable jTableKiriDaftarBuku;
    private javax.swing.JTextField jTextFieldDurasi;
    private javax.swing.JTextField jTextFieldJudulBuku;
    // End of variables declaration//GEN-END:variables
}
